// ไฟล์ตั้งค่าของ Prisma CLI: migrate, generate, validate และ studio จะอ่านไฟล์นี้
// ปกติไม่ต้องแก้บ่อย โดยไฟล์นี้ชี้ไป schema.prisma และอ่าน DATABASE_URL จาก .env
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
